# Generated by Django 5.0.6 on 2024-05-21 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_roomtype_remove_room_capacity_room_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='location',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='capacity',
            field=models.IntegerField(default=8, null=True),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
